# Generated by Django 4.0 on 2021-12-25 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=64)),
                ('requires', models.TextField()),
                ('issue', models.DateTimeField(null=True)),
                ('education', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=20)),
                ('get_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobs')),
            ],
        ),
    ]
