# Generated by Django 4.0 on 2021-12-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='education',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='id',
            field=models.CharField(max_length=130, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='position',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
