# Generated by Django 4.0 on 2021-12-31 06:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobs_education_alter_jobs_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='issue',
            field=models.DateTimeField(default=datetime.date, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_set', to='job.jobs'),
        ),
    ]
