# Generated by Django 4.0 on 2021-12-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_jobs_issue_alter_label_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='get_data',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='issue',
        ),
    ]
