# Generated by Django 4.0.1 on 2022-01-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_role_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
